package group18.misc;

import javax.swing.*;
import java.awt.*;

public class EventSelector {
    public JPanel main;
    public JButton enterButton;
    public JTextField countryField;
    public JButton backButton;
    private JLabel countryLabel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        main = new JPanel();
        main.setLayout(new GridBagLayout());
        main.setBackground(new Color(-1381654));
        panel1.add(main, BorderLayout.CENTER);
        enterButton = new JButton();
        enterButton.setBackground(new Color(-7171438));
        enterButton.setForeground(new Color(-1));
        enterButton.setText("Enter");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        main.add(enterButton, gbc);
        backButton = new JButton();
        backButton.setBackground(new Color(-7171438));
        backButton.setForeground(new Color(-1));
        backButton.setText("Back");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.weighty = 0.25;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        main.add(backButton, gbc);
        countryLabel = new JLabel();
        countryLabel.setText("Add Event: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.weighty = 0.25;
        gbc.anchor = GridBagConstraints.WEST;
        main.add(countryLabel, gbc);
        countryField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        main.add(countryField, gbc);
    }
}
