package group18.screens;

import group18.backend.Day;

import javax.swing.*;
import java.awt.*;

public class DayPanel {
    public JPanel main;
    public JLabel lbDate;
    public JLabel lbDegrees;
    public JLabel lbWeatherIcon;
    public JPanel wow;
    private Day day;

    public Day getDay() {
        return day;
    }


    public DayPanel(Day day) {
        this.day = day;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new GridBagLayout());
        wow = new JPanel();
        wow.setLayout(new GridBagLayout());
        wow.setBackground(new Color(-2103566));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        main.add(wow, gbc);
        lbDate = new JLabel();
        lbDate.setText("Date");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        wow.add(lbDate, gbc);
        lbDegrees = new JLabel();
        lbDegrees.setText("Degrees");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        wow.add(lbDegrees, gbc);
        lbWeatherIcon = new JLabel();
        lbWeatherIcon.setText("WeatherIcon");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        wow.add(lbWeatherIcon, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }
}
