package group18.screens;


import javax.swing.*;
import java.awt.*;

public class Home {
    public JPanel homePanel;

    private JPanel topButtons;
    private JPanel bottomButtons;
    private JPanel mainPanel;

    private JPanel warningsAndPlans;
    private JPanel temperatureAndImage;
    private JPanel image;

    private JLabel actualTemperature;
    private JLabel feelsLike;

    private JPanel weather;

    private JButton weekly;
    private JButton hourly;
    private JButton settings;
    private JLabel titleLabel;

    private void createUIComponents() {


    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setContentPane(new Home().homePanel);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        homePanel.setLayout(new BorderLayout(0, 0));
        bottomButtons = new JPanel();
        bottomButtons.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 5));
        homePanel.add(bottomButtons, BorderLayout.SOUTH);
        weekly = new JButton();
        weekly.setText("Weekly");
        bottomButtons.add(weekly);
        hourly = new JButton();
        hourly.setText("Hourly");
        bottomButtons.add(hourly);
        topButtons = new JPanel();
        topButtons.setLayout(new BorderLayout(0, 0));
        homePanel.add(topButtons, BorderLayout.NORTH);
        titleLabel = new JLabel();
        Font titleLabelFont = this.$$$getFont$$$(null, -1, 28, titleLabel.getFont());
        if (titleLabelFont != null) titleLabel.setFont(titleLabelFont);
        titleLabel.setText("Home");
        topButtons.add(titleLabel, BorderLayout.WEST);
        settings = new JButton();
        settings.setText("Settings");
        topButtons.add(settings, BorderLayout.EAST);
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        homePanel.add(mainPanel, BorderLayout.CENTER);
        warningsAndPlans = new JPanel();
        warningsAndPlans.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(warningsAndPlans, BorderLayout.SOUTH);
        temperatureAndImage = new JPanel();
        temperatureAndImage.setLayout(new GridBagLayout());
        mainPanel.add(temperatureAndImage, BorderLayout.CENTER);
        actualTemperature = new JLabel();
        Font actualTemperatureFont = this.$$$getFont$$$(null, -1, 28, actualTemperature.getFont());
        if (actualTemperatureFont != null) actualTemperature.setFont(actualTemperatureFont);
        actualTemperature.setText("T*C");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.25;
        gbc.weighty = 0.5;
        gbc.anchor = GridBagConstraints.SOUTHWEST;
        temperatureAndImage.add(actualTemperature, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        temperatureAndImage.add(spacer1, gbc);
        feelsLike = new JLabel();
        Font feelsLikeFont = this.$$$getFont$$$(null, -1, 18, feelsLike.getFont());
        if (feelsLikeFont != null) feelsLike.setFont(feelsLikeFont);
        feelsLike.setText("Feels like T*C");
        feelsLike.setVerticalAlignment(0);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.25;
        gbc.weighty = 0.5;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        temperatureAndImage.add(feelsLike, gbc);
        image = new JPanel();
        image.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.weightx = 0.75;
        gbc.weighty = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        temperatureAndImage.add(image, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return homePanel;
    }
}
