package group18.screens;

import group18.backend.Hour;

import javax.swing.*;
import java.awt.*;

public class HourlyPanels {
    public JLabel lbDate;
    public JLabel lbDegrees;
    private JButton addEventButton;
    public JPanel main;
    public JLabel lbHumidity;
    public JLabel lbFeelslike;
    public JLabel lbWeatherIcon;

    private Hour hour;

    public Hour getHour() {
        return hour;
    }

    public HourlyPanels(Hour hour) {
        this.hour = hour;
    }


    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new GridBagLayout());
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        main.add(panel1, gbc);
        lbDate = new JLabel();
        lbDate.setPreferredSize(new Dimension(120, 20));
        lbDate.setText("Time");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        panel1.add(lbDate, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        main.add(panel2, gbc);
        lbHumidity = new JLabel();
        lbHumidity.setPreferredSize(new Dimension(120, 20));
        lbHumidity.setText("Humidity");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        panel2.add(lbHumidity, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer2, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        main.add(panel3, gbc);
        lbFeelslike = new JLabel();
        lbFeelslike.setPreferredSize(new Dimension(120, 20));
        lbFeelslike.setText("Feels like");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        panel3.add(lbFeelslike, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel3.add(spacer3, gbc);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        main.add(panel4, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel4.add(spacer4, gbc);
        lbDegrees = new JLabel();
        lbDegrees.setPreferredSize(new Dimension(120, 20));
        lbDegrees.setText("Temperature");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 10, 5, 10);
        panel4.add(lbDegrees, gbc);
        lbWeatherIcon = new JLabel();
        lbWeatherIcon.setPreferredSize(new Dimension(80, 60));
        lbWeatherIcon.setText("WeatherIcon");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridheight = 3;
        gbc.insets = new Insets(5, 10, 5, 10);
        main.add(lbWeatherIcon, gbc);
        addEventButton = new JButton();
        addEventButton.setAlignmentY(0.8f);
        addEventButton.setMaximumSize(new Dimension(100, 100));
        addEventButton.setMinimumSize(new Dimension(100, 100));
        addEventButton.setPreferredSize(new Dimension(80, 40));
        addEventButton.setRequestFocusEnabled(false);
        addEventButton.setRolloverEnabled(false);
        addEventButton.setSelected(false);
        addEventButton.setText("+ Add Event");
        addEventButton.setVerifyInputWhenFocusTarget(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        main.add(addEventButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }
}
