package group18.screens;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SettingsView {
    public JPanel main;

    public JButton backButton;

    public JSlider coldSlider;
    public JSlider hotSlider;

    public JRadioButton onRadioButton;
    public JRadioButton offRadioButton;

    public JButton selectLocationButton;

    public JLabel belowLabel;
    public JLabel aboveLabel;

    private JPanel mainPanel;
    private JRadioButton celciusRadioButton;
    private JRadioButton fahrenheitRadioButton;
    private JPanel topPanel;
    private JPanel unitHolderPanel;
    private JPanel unitLayoutPanel;
    private JPanel thermometerIcon;
    private JLabel UnitLabel;
    private JPanel notificationHolderPanel;
    private JPanel notificationLayoutPanel;
    private JPanel notificationIcon;
    private JLabel notificationLabel;
    private JLabel coldLabel;
    private JLabel hotLabel;
    private JPanel locationHolderPanel;
    private JPanel locationLayoutPanel;
    private JLabel locationLabel;
    private JLabel selectionLabel;
    private JLabel titleLabel;

    public SettingsView() {


    }

    private void createUIComponents() {
        // TODO: place custom component creation code here


    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        main = new JPanel();
        main.setLayout(new BorderLayout(0, 0));
        Font mainFont = this.$$$getFont$$$(null, -1, 28, main.getFont());
        if (mainFont != null) main.setFont(mainFont);
        topPanel = new JPanel();
        topPanel.setLayout(new BorderLayout(0, 0));
        main.add(topPanel, BorderLayout.NORTH);
        titleLabel = new JLabel();
        Font titleLabelFont = this.$$$getFont$$$(null, -1, 28, titleLabel.getFont());
        if (titleLabelFont != null) titleLabel.setFont(titleLabelFont);
        titleLabel.setText("Settings");
        topPanel.add(titleLabel, BorderLayout.WEST);
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        main.add(mainPanel, BorderLayout.CENTER);
        unitHolderPanel = new JPanel();
        unitHolderPanel.setLayout(new BorderLayout(0, 0));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(unitHolderPanel, gbc);
        unitLayoutPanel = new JPanel();
        unitLayoutPanel.setLayout(new GridBagLayout());
        unitHolderPanel.add(unitLayoutPanel, BorderLayout.CENTER);
        unitLayoutPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        thermometerIcon = new JPanel();
        thermometerIcon.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.gridheight = 3;
        gbc.weightx = 0.75;
        gbc.weighty = 0.75;
        gbc.fill = GridBagConstraints.BOTH;
        unitLayoutPanel.add(thermometerIcon, gbc);
        UnitLabel = new JLabel();
        UnitLabel.setText("Units");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 0.125;
        gbc.anchor = GridBagConstraints.WEST;
        unitLayoutPanel.add(UnitLabel, gbc);
        celciusRadioButton = new JRadioButton();
        celciusRadioButton.setText("℃");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 0.125;
        gbc.anchor = GridBagConstraints.WEST;
        unitLayoutPanel.add(celciusRadioButton, gbc);
        fahrenheitRadioButton = new JRadioButton();
        fahrenheitRadioButton.setText("℉");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 0.125;
        gbc.anchor = GridBagConstraints.WEST;
        unitLayoutPanel.add(fahrenheitRadioButton, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        unitLayoutPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        unitLayoutPanel.add(spacer2, gbc);
        notificationHolderPanel = new JPanel();
        notificationHolderPanel.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(notificationHolderPanel, gbc);
        notificationLayoutPanel = new JPanel();
        notificationLayoutPanel.setLayout(new GridBagLayout());
        notificationHolderPanel.add(notificationLayoutPanel, BorderLayout.CENTER);
        notificationLayoutPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        notificationIcon = new JPanel();
        notificationIcon.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.gridheight = 3;
        gbc.weightx = 0.75;
        gbc.weighty = 0.75;
        gbc.fill = GridBagConstraints.BOTH;
        notificationLayoutPanel.add(notificationIcon, gbc);
        notificationLabel = new JLabel();
        notificationLabel.setText("Notifications");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 0.125;
        gbc.anchor = GridBagConstraints.WEST;
        notificationLayoutPanel.add(notificationLabel, gbc);
        onRadioButton = new JRadioButton();
        onRadioButton.setText("On");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 0.125;
        gbc.anchor = GridBagConstraints.WEST;
        notificationLayoutPanel.add(onRadioButton, gbc);
        offRadioButton = new JRadioButton();
        offRadioButton.setText("Off");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 0.125;
        gbc.anchor = GridBagConstraints.WEST;
        notificationLayoutPanel.add(offRadioButton, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        notificationLayoutPanel.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        notificationLayoutPanel.add(spacer4, gbc);
        coldLabel = new JLabel();
        coldLabel.setText("What's Cold?");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        notificationLayoutPanel.add(coldLabel, gbc);
        coldSlider = new JSlider();
        coldSlider.setForeground(new Color(-16735246));
        coldSlider.setInverted(false);
        coldSlider.setMaximum(20);
        coldSlider.setPaintLabels(false);
        coldSlider.setPaintTicks(false);
        coldSlider.setPaintTrack(true);
        coldSlider.setSnapToTicks(true);
        coldSlider.setValue(10);
        coldSlider.setValueIsAdjusting(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        notificationLayoutPanel.add(coldSlider, gbc);
        hotLabel = new JLabel();
        hotLabel.setText("What's Hot?");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        notificationLayoutPanel.add(hotLabel, gbc);
        hotSlider = new JSlider();
        hotSlider.setEnabled(true);
        hotSlider.setForeground(new Color(-917484));
        hotSlider.setMaximum(10);
        hotSlider.setPaintTrack(true);
        hotSlider.setSnapToTicks(true);
        hotSlider.setValue(5);
        hotSlider.setValueIsAdjusting(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        notificationLayoutPanel.add(hotSlider, gbc);
        belowLabel = new JLabel();
        Font belowLabelFont = this.$$$getFont$$$(null, -1, -1, belowLabel.getFont());
        if (belowLabelFont != null) belowLabel.setFont(belowLabelFont);
        belowLabel.setText("Below T*C");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.gridheight = 2;
        notificationLayoutPanel.add(belowLabel, gbc);
        aboveLabel = new JLabel();
        Font aboveLabelFont = this.$$$getFont$$$(null, -1, -1, aboveLabel.getFont());
        if (aboveLabelFont != null) aboveLabel.setFont(aboveLabelFont);
        aboveLabel.setText("Above T*C");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.gridheight = 2;
        notificationLayoutPanel.add(aboveLabel, gbc);
        locationHolderPanel = new JPanel();
        locationHolderPanel.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(locationHolderPanel, gbc);
        locationLayoutPanel = new JPanel();
        locationLayoutPanel.setLayout(new GridBagLayout());
        locationHolderPanel.add(locationLayoutPanel, BorderLayout.CENTER);
        locationLayoutPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null));
        locationLabel = new JLabel();
        locationLabel.setText("Location");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 0.125;
        gbc.anchor = GridBagConstraints.WEST;
        locationLayoutPanel.add(locationLabel, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        locationLayoutPanel.add(spacer5, gbc);
        selectionLabel = new JLabel();
        selectionLabel.setText("What is selected");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        locationLayoutPanel.add(selectionLabel, gbc);
        selectLocationButton = new JButton();
        selectLocationButton.setText("Select");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        locationLayoutPanel.add(selectLocationButton, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        main.add(panel1, BorderLayout.SOUTH);
        backButton = new JButton();
        backButton.setText("Back");
        panel1.add(backButton);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(onRadioButton);
        buttonGroup.add(offRadioButton);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(celciusRadioButton);
        buttonGroup.add(fahrenheitRadioButton);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return main;
    }
}
